#!/usr/bin/python3
import os
print("hello from test2.py")
print(os.getcwd())
prefix = "C:\\Users\\nxf48721\\Downloads\\bitbucket_repo\\vsdk\\s32v234_sdk\\tools\\gui\\netron\\python_scripts"
file_path = os.path.join(prefix, "output_from_netron_python.txt")
print(file_path)

# FOLLOWING IS FOR PYTHON3
os.umask(0)
with open(os.open(file_path, os.O_CREAT | os.O_WRONLY, 0o777), 'w') as f:
    f.write("hello from netron via python exe")

print("output generated by python script")

# EoF